name: meen_al_atlasy
description: "A new Flutter project."
publish_to: 'none'
version: 0.9.1+41

environment:
  sdk: ^3.13.3

dependencies:
  audioplayers: ^6.8.1
  file_picker: ^12.3.0
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.7.0
  package_info_plus: ^10.2.1
  path_provider: ^2.1.6
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/questions/
    - assets/sounds/
  fonts:
    - family: BalooBhaijaan2
      fonts:
        - asset: assets/fonts/baloo_bhaijaan2_medium.ttf
          weight: 500
        - asset: assets/fonts/baloo_bhaijaan2_bold.ttf
          weight: 700
        - asset: assets/fonts/baloo_bhaijaan2_extrabold.ttf
          weight: 800
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal_medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal_bold.ttf
          weight: 700
        - asset: assets/fonts/tajawal_extrabold.ttf
          weight: 800
